// SPDX-License-Identifier: LGPL-3.0-only
pragma solidity ^0.8.20;

import {IERC165} from "@openzeppelin/contracts/interfaces/IERC165.sol";

/**
 * @title ERC8039Constants
 * @dev Constants for ERC-8039 proof verification standard
 */
library ERC8039Constants {
    /**
     * @notice Magic value to be returned upon successful proof verification
     * @dev bytes4(keccak256("verifyProof(bytes,bytes)")) = 0x534f5876
     * Similar to EIP-1271's 0x1626ba7e magic value
     */
    bytes4 internal constant PROOF_MAGIC_VALUE = 0x534f5876;
}

/**
 * @title IERC8039
 * @dev Standard interface for succinct zero-knowledge proof verification (ERC-8039) for smart accounts.
 * 
 * Each verifier is specialized for ONE proof system implementation and ONE specific statement/relation.
 * For multi-system support, use application-level routing/registry patterns.
 */
interface IERC8039 is IERC165 {

    /**
     * @notice Verifies a succinct zero-knowledge proof
     * @dev The proof type is implicit in the verifier contract (one verifier = one proof system).
     * MUST NOT revert on invalid proofs; MUST return 0x00000000 instead.
     * 
     * @param publicSignals The public inputs/signals for the proof (the claims being made)
     * @param proof The serialized proof data (the cryptographic evidence)
     * @return magicValue Returns PROOF_MAGIC_VALUE if valid, 0x00000000 otherwise
     */
    function verifyProof(
        bytes calldata publicSignals,
        bytes calldata proof
    ) external view returns (bytes4 magicValue);

    /**
     * @notice Returns the proof type this verifier supports
     * @dev Used for introspection and verification.
     * Format: keccak256("protocol-implementation")
     * Examples: keccak256("GROTH16-circom"), keccak256("HONK-noir"), keccak256("SP1")
     * 
     * @return proofType The proof type identifier
     */
    function getProofType() external view returns (bytes32 proofType);

    /**
     * @notice Returns human-readable metadata describing the statement/relation being proven
     * @dev Describes what this verifier proves (not how it proves it).
     * Should include application name, purpose, and version.
     * 
     * Examples:
     * - "ZK MultiSig v1.0.0 - Threshold signature authorization"
     * - "Private signers v1.3.0 - Anonymous multisig wallet"
     * - "Age verification v2.1.0 - Prove age > 18 without revealing birthdate"
     * 
     * @return metadata Human-readable description of the statement
     */
    function metadata() external view returns (string memory metadata);
}

/**
 * @title Proof Types Library
 * @dev Identifiers for different ZK proof system implementations
 * 
 * IMPORTANT: These identifiers specify both the proof SYSTEM protocol and IMPLEMENTATION.
 * Different teams implement the same proof system protocol with different formats and interfaces.
 * 
 * Format: keccak256("protocol-implementation")
 * Example: keccak256("GROTH16-circom") vs keccak256("GROTH16-gnark")
 */
library ProofTypes {
    // ============================================================================
    // HONK Implementations
    // ============================================================================
    
    /**
     * @notice HONK via Aztec Barretenberg
     * Implementation: https://github.com/AztecProtocol/barretenberg
     * License: Apache-2.0
     */
    bytes32 public constant HONK_NOIR = keccak256("HONK-noir");
    

    // ============================================================================
    // GROTH16 Implementations
    // ============================================================================
    
    /**
     * @notice Groth16 via Circom/SnarkJS
     * Implementation: https://github.com/iden3/circom
     * Format: Solidity verifier generated by SnarkJS
     * License: MIT
     */
    bytes32 public constant GROTH16_CIRCOM = keccak256("GROTH16-circom");
    
    /**
     * @notice Groth16 via Gnark (Go implementation)
     * Implementation: https://github.com/Consensys/gnark
     * Format: Gnark-specific verifier format
     * License: Apache-2.0
     */
    bytes32 public constant GROTH16_GNARK = keccak256("GROTH16-gnark");
    

    // ============================================================================
    // PLONK Implementations
    // ============================================================================
    
    /**
     * @notice PLONK via Gnark
     * Implementation: https://github.com/Consensys/gnark
     * License: Apache-2.0
     */
    bytes32 public constant PLONK_GNARK = keccak256("PLONK-gnark");
    
    /**
     * @notice PLONK via Circom/SnarkJS
     * Implementation: https://github.com/iden3/snarkjs
     * License: MIT
     */
    bytes32 public constant PLONK_CIRCOM = keccak256("PLONK-circom");

    // ============================================================================
    // HALO2 Implementations
    // ============================================================================
    
    /**
     * @notice Halo2 via Privacy & Scaling Explorations (PSE)
     * Implementation: https://github.com/privacy-scaling-explorations/halo2
     * License: MIT / Apache-2.0
     */
    bytes32 public constant HALO2_PSE = keccak256("PLONK-HALO2-pse");
    
    /**
     * @notice Halo2 via Axiom
     * Implementation: https://github.com/axiom-crypto/halo2-lib
     * License: MIT
     */
    bytes32 public constant HALO2_AXIOM = keccak256("PLONK-HALO2-axiom");
    

    // ============================================================================
    // zkVM Implementations
    // ============================================================================
    
    /**
     * @notice SP1 zkVM by Succinct Labs
     * Implementation: https://github.com/succinctlabs/sp1
     * License: MIT / Apache-2.0
     */
    bytes32 public constant SP1 = keccak256("SP1");
    
    /**
     * @notice RISC Zero zkVM
     * Implementation: https://github.com/risc0/risc0
     * License: Apache-2.0
     */
    bytes32 public constant RISC0 = keccak256("RISC0");
}
